name: ebisu_cpp
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
description: >
  A library that supports code generation of cpp and others
dependencies:
  path: "any"
  logging: "any"

# custom <ebisu_cpp dependencies>

  magus:
   git: git://github.com/patefacio/magus
  quiver: ">=0.18.2"
  ini: ">=1.0.0"
  github: ">=2.1.2"
  sqljocky: "any"
  ebisu:
   git: git://github.com/patefacio/ebisu


# end <ebisu_cpp dependencies>

dev_dependencies:
  unittest: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_cpp dev dependencies>
# end <ebisu_cpp dev dependencies>

dependency_overrides:
# custom <ebisu_cpp dependency overrides>
# end <ebisu_cpp dependency overrides>

transformers:

# custom <ebisu_cpp transformers>
# end <ebisu_cpp transformers>

