name: ebisu_cpp
version: 0.0.4
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_cpp
description: >
  A library that supports code generation of cpp and others
dependencies:
  path: ">=1.3.0<1.4.0"

# custom <ebisu_cpp dependencies>

  magus: ">=0.0.2<0.0.5"
  quiver: ">=0.18.2<0.19.0"
  ini: ">=1.0.0<1.2.0"
  github: ">=2.1.2<2.2.0"
  sqljocky: ">=0.11.0<0.12.0"
  ebisu: ">=0.0.13<0.1.0"

# end <ebisu_cpp dependencies>

dev_dependencies:
  unittest: "any"
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_cpp dev dependencies>
# end <ebisu_cpp dev dependencies>

dependency_overrides:
# custom <ebisu_cpp dependency overrides>
# end <ebisu_cpp dependency overrides>

transformers:

# custom <ebisu_cpp transformers>
# end <ebisu_cpp transformers>

