name: ebisu_cpp
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
description: >
  A library that supports code generation of cpp and others
dependencies:
  ebisu: ">=0.0.11"
  path: ">=1.2.2 < 1.10.0"
  logging: ">=0.9.2 <0.10.0"

# custom <ebisu_cpp dependencies>

  magus:
   git: git://github.com/patefacio/magus
  quiver: ">=0.18.2"
  ini: ">=1.0.0"
  github: ">=2.1.2"
  sqljocky: "any"
  ebisu:
   git: git://github.com/patefacio/ebisu


# end <ebisu_cpp dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"
  hop: ">=0.31.0"
  hop_docgen: ">=0.1.0 <0.2.0"

# custom <ebisu_cpp dev dependencies>
# end <ebisu_cpp dev dependencies>

transformers:

# custom <ebisu_cpp transformers>
# end <ebisu_cpp transformers>

