name: ebisu_cpp
version: 0.3.26
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_cpp
description: >
  A library that supports code generation of C++ code and
  supporting infrastructure. The focus is both code (e.g. classes,
  enums, functions, ...)  and overall structure (cpp files, hpp
  files, build scripts, test files, etc.)

environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'

dependencies:

# custom <ebisu_cpp dependencies>

  args: "^1.4.0"
  ebisu:
    git: git://github.com/patefacio/ebisu.git
  id:
    git: git://github.com/patefacio/id.git

  ini:
    git:
      git://github.com/draw-dev/dart-ini.git
      
  logging: "0.11.3+2"

  path: "^1.4.1"
  petitparser: "^2.0.0"
  quiver: "2.0.0+1"
  stack_trace: "^1.9.0"
    

# end <ebisu_cpp dependencies>

dev_dependencies:

# custom <ebisu_cpp dev dependencies>

  test: "^1.3.0"

# end <ebisu_cpp dev dependencies>

dependency_overrides:
# custom <ebisu_cpp dependency overrides>
 
# end <ebisu_cpp dependency overrides>

transformers:

# custom <ebisu_cpp transformers>
# end <ebisu_cpp transformers>

