name: ebisu_cpp
version: 0.3.24
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_cpp
description: >
  A library that supports code generation of C++ code and
  supporting infrastructure. The focus is both code (e.g. classes,
  enums, functions, ...)  and overall structure (cpp files, hpp
  files, build scripts, test files, etc.)

environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:

# custom <ebisu_cpp dependencies>

  quiver: ">=0.21.0<0.25.0"  
  ini: ">=1.0.0<1.2.0"
  github: ">=2.1.2<2.2.0"
  id: "^1.0.15"  
  ebisu: "^0.7.4"
  path: "^1.3.0"
  petitparser: "^1.5.4"
  stack_trace: "^1.7.3"


# end <ebisu_cpp dependencies>

dev_dependencies:

# custom <ebisu_cpp dev dependencies>

  test: ">=0.12.0 < 0.14.0"
  drudge:
    git: git://github.com/patefacio/drudge

# end <ebisu_cpp dev dependencies>

dependency_overrides:
# custom <ebisu_cpp dependency overrides>

# end <ebisu_cpp dependency overrides>

transformers:

# custom <ebisu_cpp transformers>
# end <ebisu_cpp transformers>

