name: ebisu_cpp
version: 0.1.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_cpp
description: >
  A library that supports code generation of C++ code and
  supporting infrastructure. The focus is both code (e.g. classes,
  enums, functions, ...)  and overall structure (cpp files, hpp
  files, build scripts, test files, etc.)

dependencies:
  path: ">=1.3.0<1.4.0"

# custom <ebisu_cpp dependencies>

  magus: "^0.0.9"
  quiver: ">=0.21.0<0.22.0"  
  ini: ">=1.0.0<1.2.0"
  github: ">=2.1.2<2.2.0"
  sqljocky: ">=0.11.0<0.12.0"
  id: "^1.0.9"  
  ebisu: "^0.3.7"

# end <ebisu_cpp dependencies>

dev_dependencies:
  unittest: "any"
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_cpp dev dependencies>

  collection: "^1.1.0"

environment:
  sdk: ">=1.8.0 <2.0.0"

# end <ebisu_cpp dev dependencies>

dependency_overrides:
# custom <ebisu_cpp dependency overrides>

#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu

# end <ebisu_cpp dependency overrides>

transformers:

# custom <ebisu_cpp transformers>
# end <ebisu_cpp transformers>

